import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CurrentUserProvider from "@/context/current-user/server";
import CsrfTokenProvider from "@/context/csrf-token/server";
import { ReCaptchaProvider } from "next-recaptcha-v3";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >


        <CurrentUserProvider>
          <CsrfTokenProvider>
            <ReCaptchaProvider sitekey={process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY}>
              {children}
            </ReCaptchaProvider>
          </CsrfTokenProvider>
        </CurrentUserProvider>

        {/* {children} */}


      </body>
    </html>
  );
}
